[package]
name = "solana-multisig-wallet"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program = "=1.16.0"
tokio = "1.14.1"
borsh = "0.10.3"  # Changed to compatible version
[dev-dependencies]
solana-program-test = "=1.16.0"
solana-sdk = "=1.16.0"

[features]
no-entrypoint = []
